// Generated by gencpp from file co2_concentration/co2_trans.msg
// DO NOT EDIT!


#ifndef CO2_CONCENTRATION_MESSAGE_CO2_TRANS_H
#define CO2_CONCENTRATION_MESSAGE_CO2_TRANS_H

#include <ros/service_traits.h>


#include <co2_concentration/co2_transRequest.h>
#include <co2_concentration/co2_transResponse.h>


namespace co2_concentration
{

struct co2_trans
{

typedef co2_transRequest Request;
typedef co2_transResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct co2_trans
} // namespace co2_concentration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::co2_concentration::co2_trans > {
  static const char* value()
  {
    return "5cb65b8afe9eca1ca87a1525d6a0ffc2";
  }

  static const char* value(const ::co2_concentration::co2_trans&) { return value(); }
};

template<>
struct DataType< ::co2_concentration::co2_trans > {
  static const char* value()
  {
    return "co2_concentration/co2_trans";
  }

  static const char* value(const ::co2_concentration::co2_trans&) { return value(); }
};


// service_traits::MD5Sum< ::co2_concentration::co2_transRequest> should match
// service_traits::MD5Sum< ::co2_concentration::co2_trans >
template<>
struct MD5Sum< ::co2_concentration::co2_transRequest>
{
  static const char* value()
  {
    return MD5Sum< ::co2_concentration::co2_trans >::value();
  }
  static const char* value(const ::co2_concentration::co2_transRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::co2_concentration::co2_transRequest> should match
// service_traits::DataType< ::co2_concentration::co2_trans >
template<>
struct DataType< ::co2_concentration::co2_transRequest>
{
  static const char* value()
  {
    return DataType< ::co2_concentration::co2_trans >::value();
  }
  static const char* value(const ::co2_concentration::co2_transRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::co2_concentration::co2_transResponse> should match
// service_traits::MD5Sum< ::co2_concentration::co2_trans >
template<>
struct MD5Sum< ::co2_concentration::co2_transResponse>
{
  static const char* value()
  {
    return MD5Sum< ::co2_concentration::co2_trans >::value();
  }
  static const char* value(const ::co2_concentration::co2_transResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::co2_concentration::co2_transResponse> should match
// service_traits::DataType< ::co2_concentration::co2_trans >
template<>
struct DataType< ::co2_concentration::co2_transResponse>
{
  static const char* value()
  {
    return DataType< ::co2_concentration::co2_trans >::value();
  }
  static const char* value(const ::co2_concentration::co2_transResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CO2_CONCENTRATION_MESSAGE_CO2_TRANS_H
