// Generated by gencpp from file sound_localize/SoundBearing.msg
// DO NOT EDIT!


#ifndef SOUND_LOCALIZE_MESSAGE_SOUNDBEARING_H
#define SOUND_LOCALIZE_MESSAGE_SOUNDBEARING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sound_localize
{
template <class ContainerAllocator>
struct SoundBearing_
{
  typedef SoundBearing_<ContainerAllocator> Type;

  SoundBearing_()
    : header()
    , azimuth(0.0)
    , elevation(0.0)
    , obj_id(0)  {
    }
  SoundBearing_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , azimuth(0.0)
    , elevation(0.0)
    , obj_id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _azimuth_type;
  _azimuth_type azimuth;

   typedef double _elevation_type;
  _elevation_type elevation;

   typedef uint16_t _obj_id_type;
  _obj_id_type obj_id;





  typedef boost::shared_ptr< ::sound_localize::SoundBearing_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sound_localize::SoundBearing_<ContainerAllocator> const> ConstPtr;

}; // struct SoundBearing_

typedef ::sound_localize::SoundBearing_<std::allocator<void> > SoundBearing;

typedef boost::shared_ptr< ::sound_localize::SoundBearing > SoundBearingPtr;
typedef boost::shared_ptr< ::sound_localize::SoundBearing const> SoundBearingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sound_localize::SoundBearing_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sound_localize::SoundBearing_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sound_localize::SoundBearing_<ContainerAllocator1> & lhs, const ::sound_localize::SoundBearing_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.azimuth == rhs.azimuth &&
    lhs.elevation == rhs.elevation &&
    lhs.obj_id == rhs.obj_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sound_localize::SoundBearing_<ContainerAllocator1> & lhs, const ::sound_localize::SoundBearing_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sound_localize

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sound_localize::SoundBearing_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sound_localize::SoundBearing_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sound_localize::SoundBearing_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sound_localize::SoundBearing_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sound_localize::SoundBearing_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sound_localize::SoundBearing_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sound_localize::SoundBearing_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bde206005e1aebb168c424b301275f7c";
  }

  static const char* value(const ::sound_localize::SoundBearing_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbde206005e1aebb1ULL;
  static const uint64_t static_value2 = 0x68c424b301275f7cULL;
};

template<class ContainerAllocator>
struct DataType< ::sound_localize::SoundBearing_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sound_localize/SoundBearing";
  }

  static const char* value(const ::sound_localize::SoundBearing_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sound_localize::SoundBearing_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 azimuth\n"
"float64 elevation\n"
"uint16 obj_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sound_localize::SoundBearing_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sound_localize::SoundBearing_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.azimuth);
      stream.next(m.elevation);
      stream.next(m.obj_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SoundBearing_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sound_localize::SoundBearing_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sound_localize::SoundBearing_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "azimuth: ";
    Printer<double>::stream(s, indent + "  ", v.azimuth);
    s << indent << "elevation: ";
    Printer<double>::stream(s, indent + "  ", v.elevation);
    s << indent << "obj_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.obj_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOUND_LOCALIZE_MESSAGE_SOUNDBEARING_H
