// Generated by gencpp from file sound_localize/SoundRaw.msg
// DO NOT EDIT!


#ifndef SOUND_LOCALIZE_MESSAGE_SOUNDRAW_H
#define SOUND_LOCALIZE_MESSAGE_SOUNDRAW_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sound_localize
{
template <class ContainerAllocator>
struct SoundRaw_
{
  typedef SoundRaw_<ContainerAllocator> Type;

  SoundRaw_()
    : header()
    , data()  {
    }
  SoundRaw_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::sound_localize::SoundRaw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sound_localize::SoundRaw_<ContainerAllocator> const> ConstPtr;

}; // struct SoundRaw_

typedef ::sound_localize::SoundRaw_<std::allocator<void> > SoundRaw;

typedef boost::shared_ptr< ::sound_localize::SoundRaw > SoundRawPtr;
typedef boost::shared_ptr< ::sound_localize::SoundRaw const> SoundRawConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sound_localize::SoundRaw_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sound_localize::SoundRaw_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sound_localize::SoundRaw_<ContainerAllocator1> & lhs, const ::sound_localize::SoundRaw_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sound_localize::SoundRaw_<ContainerAllocator1> & lhs, const ::sound_localize::SoundRaw_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sound_localize

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sound_localize::SoundRaw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sound_localize::SoundRaw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sound_localize::SoundRaw_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sound_localize::SoundRaw_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sound_localize::SoundRaw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sound_localize::SoundRaw_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sound_localize::SoundRaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc47eb145a11cbe02d6c8cb8248a4099";
  }

  static const char* value(const ::sound_localize::SoundRaw_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc47eb145a11cbe0ULL;
  static const uint64_t static_value2 = 0x2d6c8cb8248a4099ULL;
};

template<class ContainerAllocator>
struct DataType< ::sound_localize::SoundRaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sound_localize/SoundRaw";
  }

  static const char* value(const ::sound_localize::SoundRaw_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sound_localize::SoundRaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int16[] data \n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sound_localize::SoundRaw_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sound_localize::SoundRaw_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SoundRaw_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sound_localize::SoundRaw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sound_localize::SoundRaw_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOUND_LOCALIZE_MESSAGE_SOUNDRAW_H
